<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <?php
            echo "<a class='navbar-brand' href='".$this->baseUrl()."/feeds/index/'> Home </a>"; ?>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       
         <li>
        <?php
            echo "<a href='".$this->baseUrl()."/feeds/add/'> Add new RSS link </a>"; ?>
        </li>
        
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>




<div class="col-md-8">

<?php 
	echo $this->form; 
	foreach ($this->links  as  $value) 
	{
	 	echo "<div list-group>";
		// echo "<ul class='list-group'>";
  	echo "<a href='".$this->baseUrl()."/feeds/list/id/".$value['id']."' class='list-group-item list-group-item-info'>".$value['path']."</a>";
	 	// echo $value['path'];
	 	
	 	// echo "</ul>";
	 	echo "</div>";
	} 

?>
</div>